publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "tail_controller"
    wait_sec_between_publish: 10

    goal_names: ["pos1"]
    pos1:
      positions: [0.0, 0.2, 0.0]
      velocities: [0.1, 0.1 , 0.1]
    pos2:
      positions: [1.0, 0.0, 1.0]
      velocities: [0.1, 0.1 , 0.1]
    pos3:
      positions: [-1.0, 0.0, 1.0]
      velocities: [0.1, 0.1 , 0.1]


    joints:
      - tail_base_shoulder_joint
      - shoulder_arm_joint
      - arm_forearm_joint

    check_starting_point: false
    starting_point_limits:
      joint1: [-0.1,0.1]
      joint2: [-0.1,0.1]