<?xml version="1.0"?>
<robot name="trx4" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Propriétés générales -->
    <xacro:property name="wheel_radius" value="0.0585" />
    <xacro:property name="wheel_length" value="0.048" />
    <xacro:property name="chassis_length" value="0.48" />
    <xacro:property name="chassis_width" value="0.22" />
    <xacro:property name="chassis_height" value="0.15" />
    <xacro:property name="axle_radius" value="0.03" />
    <xacro:property name="axle_length" value="0.20" />
    <xacro:property name="wheelbase" value="0.31" />
    <xacro:property name="suspension_travel" value="0.02" />
    <!-- Pose du LiDAR (ajuste si besoin) -->
    <xacro:property name="lidar_xyz" value="0.10 0.00 0.15"/>  <!-- +20 cm vers l'avant, +25 cm en hauteur -->
    <xacro:property name="lidar_rpy" value="0 0 0"/>           <!-- plan de scan XY, +X vers l'avant, +Z up -->


    <xacro:macro name="axle" params="name radius length mass color origin_x origin_y origin_z">
        <link name="${name}_axle_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <inertial>
                <mass value="${mass}" />
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>

        <joint name="${name}_axle_joint" type="fixed">
            <parent link="base_link" />
            <child link="${name}_axle_link" />
            <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0" />
            <axis xyz="1 0 0" />
            <limit effort="10.0" lower="-0.5" upper="0.5" velocity="1.0" />
            <dynamics damping="0.2"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="spindle" params="name radius length mass color origin_x origin_y origin_z">

        <link name="${name}_spindle_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <inertial>
                <mass value="${mass}" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>
    
        <joint name="${name}_steering_joint" type="fixed">
            <parent link="front_axle_link" />
            <child link="${name}_spindle_link" />
            <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0" />
            <axis xyz="0 0 1" />
            <limit effort="10.0" lower="-0.5" upper="0.5" velocity="1.0" />
            <!--<mimic joint="virtual_steering_joint" multiplier="1.0" offset="0.0"/>-->
        </joint>

    </xacro:macro>

    <xacro:macro name="wheel" params="name radius length mass color origin_x origin_y origin_z">
        <xacro:if value="${name == 'left_front'}">
            <xacro:property name="position" value="front" />
        </xacro:if>
        <xacro:if value="${name == 'right_front'}">
            <xacro:property name="position" value="front" />
        </xacro:if>
        <xacro:if value="${name == 'left_rear'}">
            <xacro:property name="position" value="rear" />
        </xacro:if>
        <xacro:if value="${name == 'right_rear'}">
            <xacro:property name="position" value="rear" />
        </xacro:if>

        <link name="${name}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${radius}" length="${length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <inertial>
                <mass value="${mass}" />
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0" />
            </inertial>
        </link>
        
        <xacro:if value="${position == 'front'}">
        <joint name="${name}_rotation_joint" type="fixed">
            <parent link="${name}_spindle_link" />
            <child link="${name}_wheel_link" />
            <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
        </xacro:if>

        <xacro:if value="${position == 'rear'}">
        <joint name="${name}_rotation_joint" type="fixed">
            <parent link="virtual_throttle" />
            <child link="${name}_wheel_link" />
            <origin xyz="${origin_x} ${origin_y} ${origin_z}" rpy="0 0 0" />
        </joint>
        </xacro:if>

        <!-- Joint prismatic pour la suspension 
        <joint name="${name}_suspension_joint" type="prismatic">
            <parent link="${name}_spindle_link" />
            <child link="${name}_wheel_link" />
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="0 0 1" /> 
            <limit lower="0" upper="0.02" effort="100.0" velocity="1.0" />
        </joint> -->

    </xacro:macro>

    <!-- Châssis principal -->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="5.0" />
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0" />
            <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0" ixz="0" iyz="0" />
        </inertial>
    </link>

   <!-- Joint entre le châssis et la caisse -->
    <joint name="base_chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 0" />
    </joint>

    <link name="virtual_steering">
        <visual>
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0"/>
            <geometry>
                <cylinder length="0.01" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <mass value="0.001"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="virtual_steering_joint" type="revolute">
        <parent link="front_axle_link"/>
        <child link="virtual_steering"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-0.4" upper="0.4" effort="10.0" velocity="0.0"/>
        <dynamics damping="0.2"/>
    </joint>

    <link name="virtual_throttle">
        <visual>
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0"/>
            <geometry>
                <cylinder length="0.01" radius="${wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <inertial>
            <mass value="0.001"/>
            <origin xyz="0 0 0"/>
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
        </inertial>
    </link>

    <joint name="virtual_throttle_joint" type="continuous">
        <parent link="rear_axle_link"/>
        <child link="virtual_throttle"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="10.0" velocity="10.0"/>
        <dynamics damping="0.2"/>
    </joint>

    <!-- Lien visuel du LiDAR -->
    <link name="lidar_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <!-- petit cylindre pour symboliser le capteur -->
        <geometry>
        <cylinder length="0.03" radius="0.035"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
        <cylinder length="0.03" radius="0.035"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
    </link>

    <!-- Joint fixe : base_link -> lidar_link -->
    <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${lidar_xyz}" rpy="${lidar_rpy}"/>
    </joint>

    <xacro:axle name="front" radius="0.03" length="0.25" mass="1.0" color="black" origin_x="${wheelbase / 2}" origin_y="0" origin_z="0" />
    <xacro:axle name="rear" radius="0.03" length="0.25" mass="1.0" color="black" origin_x="-${wheelbase / 2}" origin_y="0" origin_z="0" />

    <xacro:spindle name="right_front" radius="0.015" length="0.04" mass="0.2" color="grey" origin_x="0" origin_y="${axle_length / 2}"  origin_z="0" />
    <xacro:spindle name="left_front" radius="0.015" length="0.04" mass="0.2" color="grey" origin_x="0" origin_y="-${axle_length / 2}"  origin_z="0" />

    <xacro:wheel name="right_front" radius="${wheel_radius}" length="${wheel_length}" mass="0.5" color="black" origin_x="0" origin_y="0" origin_z="0" />
    <xacro:wheel name="left_front" radius="${wheel_radius}" length="${wheel_length}" mass="0.5" color="black" origin_x="0" origin_y="0" origin_z="0" />
    <xacro:wheel name="right_rear" radius="${wheel_radius}" length="${wheel_length}" mass="0.5" color="black" origin_x="0" origin_y="${axle_length / 2}" origin_z="0" />
    <xacro:wheel name="left_rear" radius="${wheel_radius}" length="${wheel_length}" mass="0.5" color="black" origin_x="0" origin_y="-${axle_length / 2}" origin_z="0" />


</robot>