trxbewi_joy_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0


trxbewi_teleop_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.8
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 0.7

    require_enable_button: true
    publish_stamped_twist: true

    enable_button: 9  # Left trigger button
    enable_turbo_button: 10  # Right trigger button
