trxbewi_joy_node:
  ros__parameters:
    deadzone: 0.05
    autorepeat_rate: 20.0


trxbewi_teleop_node:
  ros__parameters:
    axis_linear:  
      x: 1
    scale_linear:
      x: 2.25
    scale_linear_turbo:
      x: 4.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0

    require_enable_button: true
    publish_stamped_twist: true

    enable_button: 9  # Left trigger button
    enable_turbo_button: 10  # Right trigger button
