controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: bicycle_steering_controller/BicycleSteeringController

wheel_controller:
  ros__parameters:
    # steering_controllers_library
    reference_timeout: 2.0
    front_steering: true
    traction_joints_names: [traction_cmd_joint]
    steering_joints_names: [steering_cmd_joint]
    open_loop: false
    velocity_rolling_window_size: 10
    base_frame_id: chassis
    odom_frame_id: base_link
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: true
    
    # bicycle_steering_controller params
    wheelbase: 0.31
    traction_wheel_radius: 0.048